# Generated by Django 4.1.4 on 2024-02-19 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('textmaster', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='AudiometerThresholdDecimats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textmaster.audiometerthresholddecimats'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='BloodTest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textmaster.bloodtest'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='Complaints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textmaster.complaints'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='Hematology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textmaster.hematology'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='LungFunctionTest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textmaster.lungfunctiontest'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='MicroscopicExamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textmaster.microscopicexamination'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='OtherTests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textmaster.othertests'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='PhysiologicalTest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textmaster.physiologicaltest'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='SystematicExamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textmaster.systematicexamination'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='VisualTest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textmaster.visualtest'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='list_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companymaster'),
        ),
    ]
