# Generated by Django 5.0.2 on 2024-02-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='photo',
        ),
    ]
