# Generated by Django 4.1.4 on 2024-02-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('company_registration_certificate', models.ImageField(blank=True, max_length=222, null=True, upload_to='media')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, choices=[('India', 'India'), ('Australia', 'Australia'), ('Uk', 'Uk')], max_length=222, null=True)),
                ('test', models.CharField(blank=True, max_length=222, null=True)),
            ],
        ),
    ]
