# Generated by Django 5.0.2 on 2024-02-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymaster',
            name='company_registration_certificate',
        ),
    ]
