# Generated by Django 4.1.4 on 2022-12-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=222, null=True)),
                ('company_type', models.CharField(max_length=222, null=True)),
                ('company_registration_certificate', models.ImageField(max_length=222, null=True, upload_to='')),
            ],
        ),
    ]
