# Generated by Django 4.1.4 on 2022-12-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_companymaster_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
