# Generated by Django 4.1.4 on 2022-12-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companymaster_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
