# Generated by Django 4.1.4 on 2022-12-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companymaster_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='company_registration_certificate',
            field=models.ImageField(max_length=222, null=True, upload_to='img'),
        ),
    ]
