# Generated by Django 4.1.5 on 2023-02-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_companymaster_company_registration_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='company_registration_certificate',
            field=models.ImageField(blank=True, max_length=222, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
