# Generated by Django 4.1.5 on 2023-02-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companymaster_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
