# Generated by Django 4.1.5 on 2023-02-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_companymaster_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
