# Generated by Django 4.1.5 on 2023-02-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_companymaster_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='pincode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
