# Generated by Django 4.1.4 on 2023-01-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_summaryreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryreport',
            name='action',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
