# Generated by Django 4.1.4 on 2023-01-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_employeereports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeReports',
        ),
    ]
