# Generated by Django 4.1.4 on 2023-01-18 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_companymaster_company_registration_certificate'),
        ('report', '0008_remove_summaryreport_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryreport',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.companymaster'),
            preserve_default=False,
        ),
    ]
