# Generated by Django 4.1.4 on 2022-12-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='city',
            field=models.CharField(blank=True, choices=[('city1', 'city1'), ('city2', 'city2'), ('city3', 'city3'), ('city4', 'city4'), ('city5', 'city5')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='company',
            field=models.CharField(blank=True, choices=[('company1', 'company1'), ('company2', 'company2'), ('company3', 'company3')], default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='country',
            field=models.CharField(blank=True, choices=[('country1', 'country1'), ('country2', 'country2'), ('country3', 'country3'), ('country4', 'country4'), ('country5', 'country5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='state',
            field=models.CharField(blank=True, choices=[('state1', 'state1'), ('state2', 'state2'), ('state3', 'state3'), ('state4', 'state4'), ('state5', 'state5')], max_length=6, null=True),
        ),
    ]
