# Generated by Django 4.1.4 on 2022-12-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeemaster_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Others', 'Others')], max_length=6, null=True),
        ),
    ]
