# Generated by Django 4.1.4 on 2022-12-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeemaster_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='emp_added_date',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='testMaster',
        ),
    ]
