# Generated by Django 4.1.4 on 2022-12-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employeemaster_emp_added_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='test_date',
        ),
    ]
