# Generated by Django 4.1.4 on 2022-12-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employeemaster_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='test_type',
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
