# Generated by Django 4.1.4 on 2022-12-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employeemaster_test_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='employee_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
