# Generated by Django 4.1.4 on 2022-12-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_rename_audiometerthresholddecimats_employeemaster_audiometerthresholddecimats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemaster',
            old_name='bloodTest',
            new_name='BloodTest',
        ),
        migrations.RenameField(
            model_name='employeemaster',
            old_name='complaints',
            new_name='Complaints',
        ),
        migrations.RenameField(
            model_name='employeemaster',
            old_name='hematology',
            new_name='Hematology',
        ),
        migrations.RenameField(
            model_name='employeemaster',
            old_name='lungFunctionTest',
            new_name='LungFunctionTest',
        ),
        migrations.RenameField(
            model_name='employeemaster',
            old_name='microscopicExamination',
            new_name='MicroscopicExamination',
        ),
        migrations.RenameField(
            model_name='employeemaster',
            old_name='otherTests',
            new_name='OtherTests',
        ),
        migrations.RenameField(
            model_name='employeemaster',
            old_name='physiologicalTest',
            new_name='PhysiologicalTest',
        ),
        migrations.RenameField(
            model_name='employeemaster',
            old_name='systematicExamination',
            new_name='SystematicExamination',
        ),
        migrations.RenameField(
            model_name='employeemaster',
            old_name='visualTest',
            new_name='VisualTest',
        ),
    ]
