# Generated by Django 4.1.4 on 2022-12-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_rename_bloodtest_employeemaster_bloodtest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='city',
            field=models.CharField(blank=True, choices=[('Vadodara', 'Vadodara'), ('Ahemedabad', 'Ahemedabad'), ('Bharuch', 'Bharuch'), ('Rajkot', 'Rajkot'), ('Surat', 'Surat'), ('Anand', 'Anand')], max_length=15, null=True),
        ),
    ]
