# Generated by Django 4.1.4 on 2022-12-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_employeemaster_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='company',
            field=models.CharField(blank=True, choices=[('Flat Management Company', 'Flat Management Company'), ('Private Limited Company', 'Private Limited Company'), ('Unlimited Company', 'Unlimited Company'), ('Limited_Liability_Partnership', 'Limited_Liability_Partnership'), ('Proprietary', 'Proprietary'), ('Right_to_Management_Company', 'Right_to_Management_Company'), ('Community_Interest_Company', 'Community_Interest_Company'), ('Public_Limited_Company', 'Public_Limited_Company')], max_length=30),
        ),
    ]
