# Generated by Django 4.1.4 on 2022-12-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_employeemaster_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='company_name',
        ),
    ]
