# Generated by Django 4.1.4 on 2022-12-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_remove_employeemaster_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
