# Generated by Django 4.1.4 on 2022-12-28 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_companymaster_company_registration_certificate'),
        ('employee', '0020_alter_employeemaster_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companymaster'),
        ),
    ]
