# Generated by Django 4.1.4 on 2023-01-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_companymaster_company_registration_certificate'),
        ('employee', '0022_alter_employeemaster_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='list_company',
            field=models.ManyToManyField(blank=True, null=True, to='company.companymaster'),
        ),
    ]
