# Generated by Django 4.1.4 on 2023-01-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_remove_employeemaster_list_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='list_company',
        ),
    ]
