# Generated by Django 4.1.5 on 2023-01-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_employeemaster_list_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='pan_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
