# Generated by Django 4.1.5 on 2023-02-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_alter_employeemaster_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='aadhar_card_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='employee_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='fitness_certificate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='previous_certificate_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
