# Generated by Django 4.1.5 on 2023-02-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_alter_employeemaster_aadhar_card_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
