# Generated by Django 4.1.5 on 2023-02-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_alter_employeemaster_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='date_joining',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='fitness_certificate_date',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
