# Generated by Django 4.1.5 on 2023-02-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_alter_employeemaster_date_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
