# Generated by Django 4.1.5 on 2023-02-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_alter_employeemaster_fitness_certificate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='fitness_certificate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
