# Generated by Django 4.1.5 on 2023-02-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0036_alter_employeemaster_fitness_certificate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='date_joining',
            field=models.CharField(blank=True, default='2021-01-01', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='fitness_certificate_date',
            field=models.DateField(blank=True, default='2021-01-01', null=True),
        ),
    ]
