# Generated by Django 4.1.5 on 2023-02-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_alter_employeemaster_date_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='fitness_certificate_date',
            field=models.CharField(blank=True, default='2021-01-01', max_length=155, null=True),
        ),
    ]
