# Generated by Django 4.1.5 on 2023-03-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_alter_employeemaster_fitness_certificate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='company',
            field=models.CharField(blank=True, choices=[('Flat Management Company', 'Flat Management Company'), ('Private Limited Company', 'Private Limited Company'), ('Unlimited Company', 'Unlimited Company'), ('Limited Liability Partnership', 'Limited Liability Partnership'), ('Proprietary', 'Proprietary'), ('Right to Management Company', 'Right to Management Company'), ('Community Interest Company', 'Community Interest Company'), ('Public_Limited_Company', 'Public Limited Company')], max_length=30, null=True),
        ),
    ]
