# Generated by Django 4.1.5 on 2023-03-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_alter_employeemaster_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='name_pref',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=200, null=True),
        ),
    ]
