# Generated by Django 4.1.5 on 2023-03-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0040_alter_employeemaster_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='show',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=8, null=True),
        ),
    ]
