# Generated by Django 4.1.5 on 2023-04-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0042_alter_employeemaster_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
