# Generated by Django 4.1.5 on 2023-04-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0044_alter_employeemaster_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
