# Generated by Django 4.1.5 on 2023-05-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0045_alter_employeemaster_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6, null=True),
        ),
    ]
