# Generated by Django 4.1.5 on 2023-06-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0046_alter_employeemaster_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='collection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
