# Generated by Django 4.1.5 on 2023-06-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0047_alter_employeemaster_collection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
