# Generated by Django 4.1.5 on 2023-07-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0048_alter_employeemaster_collection_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='test_type',
            field=models.CharField(blank=True, choices=[('Pre', 'Pre'), ('Periodical', 'Periodical')], max_length=200, null=True),
        ),
    ]
