# Generated by Django 4.1.4 on 2022-12-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiometerthresholddecimats',
            old_name='xray_report',
            new_name='xray_reports',
        ),
    ]
