# Generated by Django 4.1.4 on 2022-12-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0002_rename_xray_report_audiometerthresholddecimats_xray_reports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiometerthresholddecimats',
            old_name='xray_reports',
            new_name='xray_report',
        ),
    ]
