# Generated by Django 4.1.4 on 2022-12-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0004_rename_s_creatinine_bloodtest_creatinine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urine_Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=222)),
                ('transparency', models.CharField(max_length=255)),
                ('deposit', models.CharField(max_length=255)),
                ('colour', models.CharField(max_length=255)),
                ('sp_gravity', models.IntegerField()),
                ('ph_reaction', models.IntegerField()),
                ('pus_cells', models.IntegerField(max_length=255)),
                ('rbc', models.IntegerField()),
                ('epi_cells', models.IntegerField()),
                ('casts', models.CharField(max_length=225)),
                ('crystals', models.CharField(max_length=255)),
                ('bacteria', models.CharField(max_length=255)),
                ('yeast_cells', models.CharField(max_length=255)),
                ('trichomonas', models.CharField(max_length=255)),
                ('amorphous_deposit', models.CharField(max_length=255)),
                ('albumin', models.CharField(max_length=255)),
                ('sugar', models.CharField(max_length=255)),
                ('acetone', models.CharField(max_length=255)),
                ('bile_pigments', models.CharField(max_length=255)),
                ('bile_salts', models.CharField(max_length=255)),
                ('urobilinogen', models.CharField(max_length=255)),
            ],
        ),
    ]
