# Generated by Django 4.1.4 on 2022-12-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0005_urine_examination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='creatinine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
