# Generated by Django 4.1.4 on 2022-12-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0006_alter_bloodtest_creatinine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='alkaline_phosphatase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='blood_urea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='bun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='ch_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='direct_bilirubin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='direct_hdl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='fasting_blood_glucose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='ggt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='hcv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='indirect_bilirubin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='ldl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='lh_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='plcc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='plcr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='post_prandial_blood_glucose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='psa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='random_blood_glucose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='rdw_sd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='sgot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='sgpt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='total_bilirubin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='total_cholesterol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='triglycerides',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='vitaminb12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='vitamind3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='vldl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
