# Generated by Django 4.1.4 on 2022-12-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0009_alter_othertests_acid_fast_bacilli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urine_examination',
            name='pus_cells',
            field=models.IntegerField(),
        ),
    ]
