# Generated by Django 4.1.4 on 2023-01-12 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_employeemaster_list_company'),
        ('test_master', '0014_bloodtest_btest_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='othertests',
            name='othertest_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.employeemaster'),
            preserve_default=False,
        ),
    ]
