# Generated by Django 4.1.4 on 2023-01-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0018_audiometerthresholddecimats_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiometerthresholddecimats',
            old_name='audio',
            new_name='audio_employee',
        ),
    ]
