# Generated by Django 4.1.4 on 2023-01-18 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_employeemaster_list_company'),
        ('test_master', '0020_alter_othertests_othertest_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='audio_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeemaster'),
        ),
    ]
