# Generated by Django 4.1.4 on 2023-01-18 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_employeemaster_list_company'),
        ('test_master', '0021_alter_audiometerthresholddecimats_audio_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='audiometery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='for_left_ear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='for_right_ear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='left_ac_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='left_ac_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='left_ac_4000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='left_ac_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='left_ac_5000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='left_bc_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='left_bc_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='left_bc_4000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='left_bc_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='left_bc_5000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='right_ac_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='right_ac_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='right_ac_4000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='right_ac_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='right_ac_5000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='right_bc_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='right_bc_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='right_bc_4000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='right_bc_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='right_bc_5000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='ultra_sonographic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='xray_report',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='basophils',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='blood_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='eosinophils',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='esr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='hct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='hemoglobin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='hlogy_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeemaster'),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='leucocytes_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='lymphocytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='mch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='mchc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='mcv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='monocytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='mpv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='pct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='pdw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='peripheral_smear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='platelet_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='polymorphs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='rdw_cv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='total_wbc_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='fef50',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='fef50_per_predicted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='fef50_predicted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='fev1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='fev1_fvc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='fev1_fvc_per_predicted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='fev1_fvc_predicted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='fev1_per_predicted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='fev1_predicted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='fvc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='fvc_per_predicted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='fvc_predicted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='lung_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeemaster'),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='peak_exp_flow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='pefr_per_predicted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='pefr_predicted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='spirometry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microscopicexamination',
            name='casts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microscopicexamination',
            name='crystais',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microscopicexamination',
            name='epithelial_cells',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microscopicexamination',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='microscopicexamination',
            name='pus_cells',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microscopicexamination',
            name='red_blood_cells',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microscopicexamination',
            name='urine_report',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='blood_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='chest_on_expiration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='chest_on_inspiration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeemaster'),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='heart_sound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='hips',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='remarks_and_advice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='waist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='waist_hip_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systematicexamination',
            name='abdomen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systematicexamination',
            name='breath_sound',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systematicexamination',
            name='cardiovascular_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systematicexamination',
            name='cns',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systematicexamination',
            name='ecg_report',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systematicexamination',
            name='genito_urinary_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systematicexamination',
            name='other_finding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systematicexamination',
            name='respiratory_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systematicexamination',
            name='skeletal_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systematicexamination',
            name='skin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='systematicexamination',
            name='sys_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeemaster'),
        ),
        migrations.AlterField(
            model_name='testmaster',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testmaster',
            name='test_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testmaster',
            name='test_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testmaster',
            name='test_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='acetone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='albumin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='amorphous_deposit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='bacteria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='bile_pigments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='bile_salts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='casts',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='colour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='crystals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='deposit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='epi_cells',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='ph_reaction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='pus_cells',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='rbc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='sp_gravity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='sugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='transparency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='trichomonas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='urine_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeemaster'),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='urobilinogen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='volume',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='yeast_cells',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='distance_vision_with_glass',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='distance_vision_with_glass_right',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='distance_vision_without_glass',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='distance_vision_without_glass_right',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='nearvision_with_glass',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='nearvision_with_glass_right',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='nearvision_without_glass',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='nearvision_without_glass_right',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='vision_remark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
