# Generated by Django 4.1.5 on 2023-02-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0026_alter_audiometerthresholddecimats_audiometery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiometerthresholddecimats',
            name='right_ac_500',
            field=models.FloatField(blank=True, max_length=222, null=True),
        ),
    ]
