# Generated by Django 4.1.5 on 2023-02-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0032_alter_lungfunctiontest_fef50_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiologicaltest',
            name='blood_pressure',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='chest_on_expiration',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='chest_on_inspiration',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='heart_sound',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='height',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='hips',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='pulse',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='remarks_and_advice',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='waist',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='waist_hip_ratio',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='weight',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
