# Generated by Django 4.1.5 on 2023-02-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_alter_employeemaster_pan_number'),
        ('test_master', '0033_alter_physiologicaltest_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualtest',
            name='visual_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeemaster'),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='distance_vision_with_glass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='distance_vision_with_glass_right',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='distance_vision_without_glass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='distance_vision_without_glass_right',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='nearvision_with_glass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='nearvision_with_glass_right',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='nearvision_without_glass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='nearvision_without_glass_right',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='vision_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
