# Generated by Django 4.1.5 on 2023-02-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0036_alter_othertests_ag_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microscopicexamination',
            name='casts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='microscopicexamination',
            name='crystais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='microscopicexamination',
            name='epithelial_cells',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='microscopicexamination',
            name='pus_cells',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='microscopicexamination',
            name='red_blood_cells',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='microscopicexamination',
            name='urine_report',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
