# Generated by Django 4.1.5 on 2023-03-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0040_alter_employeemaster_first_name_and_more'),
        ('test_master', '0042_alter_audiometerthresholddecimats_audiometery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complaints_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeemaster'),
        ),
        migrations.AddField(
            model_name='microscopicexamination',
            name='micro_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeemaster'),
        ),
    ]
