# Generated by Django 4.1.5 on 2023-03-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0043_complaints_complaints_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physiologicaltest',
            old_name='employee',
            new_name='phy_employee',
        ),
    ]
