# Generated by Django 4.1.5 on 2024-02-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0046_urine_examination_crystais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urine_examination',
            name='casts',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='urine_examination',
            name='pus_cells',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
