# Generated by Django 4.1.5 on 2024-02-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0047_alter_urine_examination_casts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urine_examination',
            name='crystais',
        ),
        migrations.RemoveField(
            model_name='urine_examination',
            name='epithelial_cells',
        ),
        migrations.RemoveField(
            model_name='urine_examination',
            name='material',
        ),
        migrations.RemoveField(
            model_name='urine_examination',
            name='red_blood_cells',
        ),
        migrations.RemoveField(
            model_name='urine_examination',
            name='urine_report',
        ),
    ]
