# Generated by Django 4.1.5 on 2024-02-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0048_remove_urine_examination_crystais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urine_examination',
            name='crystais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urine_examination',
            name='epithelial_cells',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urine_examination',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urine_examination',
            name='red_blood_cells',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urine_examination',
            name='urine_report',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
