# Generated by Django 4.1.5 on 2024-02-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0049_urine_examination_crystais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtest',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O-positive', 'O-positive'), ('O-negative', 'O-negative'), ('A-positive', 'A-positive'), ('A-negative', 'A-negative'), ('B-positive', 'B-positive'), ('B-negative', 'B-negative'), ('AB-positive', 'AB-positive'), ('AB-negative', 'AB-negative')], max_length=200, null=True),
        ),
    ]
