# Generated by Django 4.1.5 on 2024-02-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0050_bloodtest_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='family_health_history',
            field=models.CharField(blank=True, choices=[('hypertension', 'hypertension'), ('diabetes', 'diabetes')], max_length=200, null=True),
        ),
    ]
