# Generated by Django 4.1.5 on 2024-02-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_master', '0051_alter_complaints_family_health_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='family_class_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='family_health_history',
        ),
        migrations.AddField(
            model_name='complaints',
            name='family_health_history',
            field=models.ManyToManyField(blank=True, null=True, to='test_master.family_class_type'),
        ),
    ]
